### ISSUE TITLE
Support user capture templates

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar-org-roam#11]
This is related to #2, but am not sure precisely how (see that discussion).

In any case, I think this is the primary missing feature for v1.0. I have hence tagged it with that milestone.

**Comment by danielclucas** [comment]
I am trying to integrate citar/citar-org-roam with org-roam's capture functionality. I am not sure what exact solution was arrived at in https://github.com/emacs-citar/citar-org-roam/issues/2. I see that you have provided the internal function 
```lisp
(defun citar-org-roam--create-capture-note (citekey entry)
    "Open or create org-roam node for CITEKEY and ENTRY."
   ;; adapted from https://jethrokuan.github.io/org-roam-guide/#orgc48eb0d
    (let ((title (citar-format--entry
                   citar-org-roam-note-title-template entry)))
     (org-roam-capture-
      :templates
      '(("r" "reference" plain "%?" :if-new
         (file+head
          "%(concat
 (when citar-org-roam-subdir (concat citar-org-roam-subdir \"/\")) \"${citekey}.org\")"
          "#+title: ${title}\n")
         :immediate-finish t
         :unnarrowed t))
      :info (list :citekey citekey)
      :node (org-roam-node-create :title title)
      :props '(:finalize find-file))
     (org-roam-ref-add (concat "@" citekey))))
```
Do you see this as the main entry point for a user to implement org-roam capture functionality? 

The key difference I see between this function and the one in https://jethrokuan.github.io/org-roam-guide/ is that Jethro's method of accessing the citekey and entry as the `car` and `cdr` of a key value pair retrieved by `citar-select-ref`  no longer works with Citar since a breaking change that you mention in https://github.com/emacs-citar/citar/issues/696. What would be the best way to get the key and associated entry to pass into `citar-org-roam--create-capture-note` as arguments?

**Comment by roshanshariff** [comment]
`org-capture` seems to have a (newish) hook feature that allows arbitrary functions to be run at various points in the capture process. We might be able to use such a function to prompt for a citation and expand template fields in the captured entry.

See https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/etc/ORG-NEWS?id=7f3a6cf6e72fe9968c6ef32211c754b7fe0172b6

**Comment by bdarcus** [comment]
I think that may be setting the stage for merging doct as a new, better, template approach for org-capture.

**Comment by roshanshariff** [comment]
Ah, interesting! I hadn't seen doct before, but it looks intriguing. I'll dig deeper into it when I can.

**Comment by bdarcus** [comment]
Here's the initial patch, and explanation.

https://lists.gnu.org/archive/html/emacs-orgmode/2022-09/msg00677.html
