### ISSUE TITLE
Review, refine `citar-org-roam--create-capture-note `

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar-org-roam#2]
This function is adapted from @jethrokuan's post:

https://jethrokuan.github.io/org-roam-guide/#orgc48eb0d

I'm not super familiar with the org-roam capture system, so would help if someone who is can review this and suggest any changes. 

Aside from fixing the variable bug noted in the code, it might be nice if this was accessible and configurable from `org-roam-capture`, which it isn't now. Per below, I'm still unsure of the ideal UI and config details here.

Note: this reflects changes in https://github.com/emacs-citar/citar/pull/634; also, org citations aren't allowed in property drawers, so I changed that.

**Comment by bdarcus** [comment]
> For example, it can store notes as sub-headings inside a single file, insert the last stored Org link, prompt for certain template fields that are expanded within the note, etc.

OK, those are good reasons to keep it and fix it then.

It occurs to me also, as I noted in an edit above, that if possible, it'd be good to be able to add a ref note from org, using capture.

So I merged that branch to main.

**Comment by Vidianos-Giannitsis** [comment]
Hi, I gave this a look and I am pretty sure there is a small mistake in the function. Aren't the :node and :props arguments supposed to go to `org-roam-capture-` and not the list generated in :info? If I am not mistaken that is something that needs to be changed.
```
(defun citar-org-roam--create-note (key entry) 
   "Create org-roam node for KEY and ENTRY." 
   ;; adapted from https://jethrokuan.github.io/org-roam-guide/#orgc48eb0d 
   ;; FIX doesn't work ATM. 
   (let ((title (citar-format--entry 
                 "${author editor} :: ${title}" entry))) 
     (org-roam-capture- 
      :templates 
      '(("r" "reference" plain "%?" :if-new 
         (file+head 
          "%(concat citar-org-roam-subdir \"/\" \"${key}.org\")" 
          ":PROPERTIES: 
 :ROAM_REFS: @${key} 
 :END: 
 #+title: ${title}\n") 
         :immediate-finish t 
         :unnarrowed t)) 
      :info (list :citekey key)
      :node (org-roam-node-create :title title) 
      :props '(:finalize find-file))))
```

I have tinkered a bit with the org-roam capture system (mainly for making my own specialized templates) so I can probably help with this, but I have 2 questions. I wanted to run this function as a test to try its behavior but I am a bit confused with the `entry` argument. What are you supposed to pass to it? And my other question is what exactly does this plan to achieve. Is it just supposed to create a ref node for a bibtex entry with the minimum amount of metadata for it to be functional or do you want to add more things to it? I am asking because how I look at it this should be a working function for just initializing the note, but there are other cool things you could add to something like this.

**Comment by Vidianos-Giannitsis** [comment]
I see, I will probably play around with this more and suggest anything I come up with.

**Comment by bdarcus** [comment]
PS - I just pushed your suggested fix, @Vidianos-Giannitsis, but haven't had time to test it.

**Comment by bdarcus** [comment]
Also, just realized there was a bug on the citar side, that I just fixed.

Turning on `citar-org-roam-mode` and then running `citar-open` should work again (as it did before I made a late change and forgot to test).

I just added  a screenshot to the README.

**Comment by bdarcus** [comment]
> Hi! Wouldn't there be a way to simply use the default `org-roam-capture-templates` like it was possible with the old `(citar-open-note-function 'orb-citar-edit-note)` setting? 

IDK. Why I was asking for help here.

> Also, is there a way to configure `citar-org-roam-subdir` from outside the citar-org-roam.el file?

Sure; it's a defcustom.

Or did you mean something different?

**Comment by bdarcus** [comment]
> I'll fix the spurious "/". Should be set to `nil` in that case.

Fixed in https://github.com/emacs-citar/citar-org-roam/commit/e9f1b68bfc3d27022c7a10595dd89d2e3a41bd0f

> ... but it proceeds to directly create the note and moving to it without opening a proper capture buffer.

Yes; that's just how it works ATM.

If we know we're creating a bibliographic note here, because calling `citar-open-notes`, do we need a capture buffer?

If yes, what's one of the enhancement I don't know how to implement, and I don't have time ATM to figure it out.

Perhaps the others in this thread can.

**Comment by bdarcus** [comment]
It would define the value of capture for this particular use case, however?

Why would it be valuable to include this?

**Comment by roshanshariff** [comment]
I don't personally use Org Capture very much, but I can imagine how its features might fit into someone's workflow:
* Having multiple notes in a file, and possibly choosing which file to put them in. You might have different capture templates for different projects, and choose to put all the notes relating to a project in its own file.
* If you're keeping a reading journal, you might want to use the the "datetree" feature to file each note under the current date.
* The capture template can include the selected region. You might use this to store relevant snippets as you encounter them.

Pretty much any time you otherwise want to use Org Capture, but would like the template to be filled in using data from a Citar reference.

**Comment by lazzalazza** [comment]
I totally agree with @roshanshariff. I also like the way in which Org Capture lets you preemptively confirm or discard the new buffer without automatically saving it. Plus, people that integrated Org Capture in their workflow might like at least to have the option of using their general templates even with Citar...

**Comment by bdarcus** [comment]
Maybe we should have two note sources:

1. The default citar one (without capture)
2. A capture one

I still don't understand how the UX would work on the second though.

**Comment by lazzalazza** [comment]
Here are some pictures of my UX.

<img width="1512" alt="immagine" src="https://user-images.githubusercontent.com/60494153/179704656-ef828092-94d3-4d40-98e7-a99fef5a0fcd.png">
<img width="1512" alt="immagine" src="https://user-images.githubusercontent.com/60494153/179704681-64cd2b7d-8a77-4a44-afc2-c6a837f1f24e.png">
<img width="1512" alt="immagine" src="https://user-images.githubusercontent.com/60494153/179704727-2cce33cb-0dad-46fb-8031-e2d107d53e55.png">

Two more things:

1. I still can't  modify `citar-org-roam-notes-config` with a `setq` from my init file: it would be nice, at least for the moment, to have a way to customize the note-creating function from outside citar-org-roam.el.

2. If I try to create a note with the standard `citar-org-roam--create-capture-note` command, after setting the `citar-org-roam-subdir` to `""`, I get a "file not found" and "buffer read-only" error.

**Comment by bdarcus** [comment]
Thanks for the screenshots!

> 2\. If I try to create a note with the standard `citar-org-roam--create-capture-note` command, after setting the `citar-org-roam-subdir` to `""`,

As I mentioned to you earlier (twice): has to be set to `nil` ;-)

**Comment by lazzalazza** [comment]
Sorry, my bad! Thanks!

**Comment by bdarcus** [comment]
I do also want to mention that ORB will be supporting the new citar note API, and could in theory even use parts of this package.

So these are potentially complementary.

And to go back to your other point above:

> I still can't modify citar-org-roam-notes-config with a setq from my init file: it would be nice, at least for the moment, to have a way to customize the note-creating function from outside citar-org-roam.el.

I mean you have two options ATM:

You can create and register your own note source, and then use that.

I think you can use `setf` (not `setq`)  to change the existing note source.

I'm not sure if @roshanshariff has any thoughts about how we should handle this piece. I was really contemplating two options:

1. per above, use note source plist for this
2. add a defcustom just for `:create`

IDK myself.

This is still kind of an experimental package at this point, that I put together to test out what we needed for the new citar notes API. It still needs a bit of work before we release it more formally.

**Comment by bdarcus** [comment]
Granting there's more work to be done here, anyone see any problem with announcing this along with citar 1.0 (soon)?

**Comment by bdarcus** [comment]
@lazzalazza - can you try this?

```elisp
(defconst orb-citar-source
  (list :name "Org-Roam Notes"
        :category 'org-roam-node
        :items #'citar-org-roam--get-candidates
        :hasitems #'citar-org-roam-has-notes
        :open #'citar-org-roam-open-note
        :create #'orb-citar-edit-note
        :annotate #'citar-org-roam--annotate))
        
(citar-register-notes-source
 'orb-citar-source)

(setq citar-notes-source 'orb-citar-source))
```

**Comment by lazzalazza** [comment]
Hi! I put the last line of code in my config file and the rest of it in citar-org-roam.el and it works like a charm (there's an extra parens at the end though)...
Thank you so much!

**Comment by bdarcus** [comment]
Really the only change should be using ORB to create new notes. Is that the case?

**Comment by lazzalazza** [comment]
It is! It works!

**Comment by bdarcus** [comment]
> Maybe we should have two notes sources:

Maybe we should do three, including the orb one I posted just above?

**Comment by bdarcus** [comment]
> I know that Org Capture is a very user-oriented feature and doesn't easily allow other packages to participate in the note formatting (for example to extend its template system, except by including arbitrary Elisp code). Org-Roam-Bibtex goes to heroic lengths to make it possible.

I wonder if there are tweaks to upstream that could make this easier?

**Comment by danielclucas** [comment]
I am trying to integrate citar/citar-org-roam with org-roam's capture functionality. I am not sure what exact solution has been arrived at on this issue. I see that you have provided the internal function 
`citar-org-roam--create-capture-note`. Do you see this function as the main entry point for a user to implement org-roam capture functionality? 

The key difference I see between this function and the one in https://jethrokuan.github.io/org-roam-guide/ is that Jethro's method of accessing the citekey and entry as the `car` and `cdr` of a key value pair retrieved by `citar-select-ref`  no longer works with Citar since a breaking change that you mention in https://github.com/emacs-citar/citar/issues/696. What would be the best way to get the key and associated entry to pass into `citar-org-roam--create-capture-note` as arguments?

**Comment by bdarcus** [comment]
Ideally we can modify `citar-org-roam--create-capture-note` to allow users to define their own capture templates. But I"m not sure how best to do that, and haven't had time to figure it out 

In the meantime, see:

https://github.com/emacs-citar/citar/wiki/Notes-configuration#org-roam-bibtex

**Comment by danielclucas** [comment]
`citar-get-entry` was exactly the function I needed, thank you!
